CREATE TABLE IF NOT EXISTS client ( clientId INTEGER PRIMARY KEY AUTOINCREMENT, realm TEXT NOT NULL, email TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS client_unique_realm ON client (realm);
CREATE TABLE IF NOT EXISTS stats ( statId INTEGER PRIMARY KEY AUTOINCREMENT, clientId INTEGER NOT NULL, sampleEpoc INTEGER NOT NULL, cpuLoad REAL NOT NULL, freeRam INTEGER NOT NULL, numRunProcs INTEGER NOT NULL );
